### ISSUE TITLE
Use pure Rust library instead of flate2

### ISSUE THREAD

**Issue by retep998** [PistonDevelopers/image-png#2]
Since `png` depends on `flate2`, which relies on `miniz.c`, this means that to build this crate people need to have a C/C++ compiler setup, which is annoying for users on Windows who just install Rust and expect things to work.

https://github.com/PistonDevelopers/image/issues/419

**Comment by Shnatsel** [comment]
This is also a memory safety / security concern.

Unfortunately, there doesn't seem to be a DEFLATE encoder written in Rust - "rust-compress" and "inflate" crates only provide decoders.

**Comment by ZoomRmc** [comment]
What about Carol Nichols' Zopfli rewrite?
[carols10cents/zopfli](https://github.com/carols10cents/zopfli)
