### ISSUE TITLE
'afl-coverage' is now 'afl'

### ISSUE THREAD

**Issue by frewsxcv** [PistonDevelopers/image-png#21]
https://github.com/frewsxcv/afl.rs/commit/41d37ed37bb66202fe59cbfef59720e97603099a

This crate still refers to the old title `'afl-coverage'`

**Comment by bvssvni** [comment]
Could not find it in Cargo.toml. Sure this is posted on the right project?

**Comment by nwin** [comment]
There is a sub-project in png-afl.

**Comment by frewsxcv** [comment]
https://github.com/PistonDevelopers/image-png/blob/0c720be346910cb159ec74b9db3c6fc485b5a162/png-afl/Cargo.toml#L10-L14
