### ISSUE TITLE
I think the new version of bitflags broke png

### ISSUE THREAD

**Issue by Ogeon** [PistonDevelopers/image-png#24]
It was just recently updated to version 0.5.0, which included a change that makes flags private by default. [Here's an example of it failing](https://travis-ci.org/Ogeon/palette/jobs/112504946#L251).

**Comment by Ogeon** [comment]
Never mind. Turns out `image` were using an old version.

**Comment by eddyb** [comment]
This is a problem: `cargo update` went from `0.3.2` to `0.5.0` on `image`. I'm not sure there's a way to stop the update from happening.

**Comment by Ogeon** [comment]
I think png 0.3.1 was using wildcard dependencies, which caused it to just keep pulling new versions of bitflags.

**Comment by Ogeon** [comment]
It's totally a mistake from my end. We have been depending on image 0.4.* all the time, which is from October 2015. I'm not sure why, but that's an other question.

**Comment by eddyb** [comment]
I had this problem yesterday after a `cargo update` and no old `image` versions hardcoded.

**Comment by Ogeon** [comment]
¯\_(ツ)_/¯
