### ISSUE TITLE
Problem with color indexing

### ISSUE THREAD

**Issue by Yamakaky** [PistonDevelopers/image-png#39]
```
    let input = BufReader::new(File::open("f.png").unwrap());
    let decoder = png::Decoder::new(input);
    let (infos, rest) = decoder.read_info().unwrap();
    println!("{}", infos.color_type as u16);
```
```shell
# file f.png
one.png: PNG image data, 64 x 64, 4-bit colormap, non-interlaced
```

Output: `2`, should be `3`

**Comment by nwin** [comment]
No the result is correct, the structure contains the output `ColorType` (which is why it is called `OutputInfo`). Admittedly, this is should be documented better. 

You need to use `decoder.set(png::TRANSFORM_IDENTITY)` in order to receive the raw data.

**Comment by Yamakaky** [comment]
Oh, thanks
