### ISSUE TITLE
"invalid uncompressed block len" when decoding white_color.png from CSS2.1 test suite

### ISSUE THREAD

**Issue by mbrubeck** [PistonDevelopers/image-png#4]
Decoding the following image results in `FormatError("invalid uncompressed block len")`:

https://github.com/servo/servo/blob/master/tests/wpt/css-tests/css21_dev/html4/support/white_color.png

**Comment by mbrubeck** [comment]
It appears that `len == 0x03FF` and `nlen = 0xF800`.  This is indeed off by 1 bit.

**Comment by nwin** [comment]
So this could be closed for now?

In principle one could just ignore the `nlen` field and hope that it works.

**Comment by mbrubeck** [comment]
No, I think there's a bug somewhere. There's not actually an uncompressed block there.

The `03ff f800` bytes are at offset 0x0b64, almost at the end of the file (file size = 0x0b7b). libpng's pngcheck reports:

```
$ pngcheck -v ~/Downloads/white_color.png 
File: /home/mbrubeck/Downloads/white_color.png (2939 bytes)
  chunk IHDR at offset 0x0000c, length 13
    100 x 100 image, 32-bit RGB+alpha, non-interlaced
  chunk pHYs at offset 0x00025, length 9: 2835x2835 pixels/meter (72 dpi)
  chunk iCCP at offset 0x0003a, length 2639
    profile name = Photoshop ICC profile, compression method = 0 (deflate)
    compressed profile = 2616 bytes
  chunk cHRM at offset 0x00a95, length 32
    White x = 0.31269 y = 0.32899,  Red x = 0.63999 y = 0.33001
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.05999
  chunk IDAT at offset 0x00ac1, length 166
    zlib: deflated, 32K window, maximum compression
  chunk IEND at offset 0x00b73, length 0
No errors detected in /home/mbrubeck/Downloads/white_color.png (6 chunks, 92.7% compression).
```

but pngcheck.rs says:

```
$ cargo run --example pngcheck -- -v ~/Downloads/white_color.png 
     Running `target/debug/examples/pngcheck -v /home/mbrubeck/Downloads/white_color.png`
File: /home/mbrubeck/Downloads/white_color.png (10240) bytes
  chunk IHDR at offset 0x0000c, length 13
    100 x 100 image, 8-bit RGB+alpha, non-interlaced
  chunk pHYs at offset 0x00025, length 9
  chunk iCCP at offset 0x0003a, length 2639
  chunk cHRM at offset 0x00a95, length 32
  chunk IDAT at offset 0x00ac1, length 166: invalid uncompressed block len
ERRORS DETECTED in /home/mbrubeck/Downloads/white_color.png
```

**Comment by ivan** [comment]
I see the same error when decoding this rgb48be PNG https://web.archive.org/web/20160124093256/http://ludios.org/tmp/wizard.png
![wizard](https://cloud.githubusercontent.com/assets/4458/12535516/e1d09c8e-c27d-11e5-9712-26c4ca29334a.png)

(This does not happen for all rgb48be PNGs.)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/inflate/pull/2. Reopen if still a problem.
