### ISSUE TITLE
This is also an encoder library!

### ISSUE THREAD

**Issue by est31** [PistonDevelopers/image-png#42]
I see you also have encoder functionality. The piston crate in fact gives its to its users, so I assume its mature?

Would it be possible to update the github description of the repo and the description in Cargo.toml to reflect that?

I'm coming from a discussion in IRC where someone erroneously assumed (probably due to this misinformation) that this crate can only decode.

Thanks!

**Comment by LaylConway** [comment]
I think you are mistaken https://docs.rs/png/0.5.2/png/#encoder

**Comment by est31** [comment]
and what about https://github.com/PistonDevelopers/image-png/blob/master/src/encoder.rs

and https://github.com/PistonDevelopers/image#21-supported-image-formats

(note the encode column)

**Comment by daiheitan** [comment]
@est31 Yes, you can check the source code of piston's image repo. The png encoder is generally a call to this crate's encoder.

**Comment by kosinix** [comment]
Can confirm that it can encode. I can volunteer to send a pull request to update the doc but I am not sure if there are issues with the encoder that we aren't aware of.

**Comment by nwin** [comment]
Well, the problem is that the encoder isn’t written in Rust. As such we are depending on `flate2`. Afaik there are now also zlib encoders available in Rust.

**Comment by kosinix** [comment]
Is it possible to swap flate2 with [https://github.com/sile/libflate](https://github.com/sile/libflate)?

**Comment by est31** [comment]
@nwin not anymore: #46 . Even if the encoder part is not pure rust, its still an encoder library too.

**Comment by eddyb** [comment]
(reopened on behalf of @est31 on IRC)

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/image-png/pull/49

**Comment by est31** [comment]
Thanks! Its perfect now :)

**Comment by nwin** [comment]
I see, #44 just opened the source. Sorry for that.
