### ISSUE TITLE
Incorrect color_type when decoding

### ISSUE THREAD

**Issue by Phrohdoh** [PistonDevelopers/image-png#55]
My PNG is indexed but this crate reads it as RGB so `buf` is being filled with RGB bytes instead of palette indices.

```sh
$ pngcheck chariot-nope-64x64.png
OK: chariot-nope-64x64.png (64x64, 8-bit palette, non-interlaced, -22.7%).
```

```rust
let png_path = "/path/to/this.png";
let f = std::fs::File::open(png_path).expect(&format!("Failed to open {}", &png_path));
let decoder = png::Decoder::new(f);
let (info, mut reader) = decoder.read_info().expect("Failed to 'read_info' ???");
let mut buf = vec![0; info.buffer_size()];
reader.next_frame(&mut buf).expect("Failed to read frame");

// This fails!
assert_eq!(png::ColorType::Indexed, info.color_type);
```

![chariot-nope-64x64](https://cloud.githubusercontent.com/assets/4861023/26034694/0d698f2a-3886-11e7-922f-40266ad92833.png)

https://github.com/PistonDevelopers/image-png/blob/104b08036bf926d10fa96cec40b3134d337cccbf/src/decoder/mod.rs#L328 is suspect.

If I need to hack together a workaround myself I will, or if someone will help me fix the actual issue and get that merged I'm more than happy to do so.

Progress on a project of mine is stalled while this is an issue.

Perhaps I am using the library incorrectly. I would be happy to be corrected and close this.

**Comment by nwin** [comment]
Have a look a few lines above. By default the library expands the paletted bytes. `decoder.set(png::TRANSFORM_IDENTITY)` should do the trick. I'm on mobile and don't remember the exact API.

**Comment by Phrohdoh** [comment]
Thank you, that solved my issue, I'll close this ticket!

Do you know the reasoning for that default setting?
By default, IMO, only transforms I explicitly ask for should be applied.

**Comment by nwin** [comment]
The default setting aims towards the most common use case of just wanting to have the image without having to care about nifty details like paletted images or interlacing.
