### ISSUE TITLE
Access to Metadata

### ISSUE THREAD

**Issue by robbym** [PistonDevelopers/image-png#57]
I would like access to a png's textual metadata. Is there a way to get access to the iTXt, tEXt, and zTXt chunks?

**Comment by nwin** [comment]
Only very rough through `StreamingDecoder`. You can have a look at https://docs.rs/png/0.6.2/src/png/decoder/mod.rs.html#100 on how to use it. You would have to combine all `PartialChunk`s between `ChunkStart` and `ChunkEnd` of the desired chunks.

**Comment by robbym** [comment]
So I tried using StreamingDecoder, and decoded an image containing a zTXt chunk 10 bytes at a time, but I did not get `PartialChunk`s between `ChunkBegin` and `ChunkComplete`:
```
10, Nothing
6, ChunkBegin(13, [73, 72, 68, 82])
10, Nothing
3, Header(1024, 992, Eight, RGBA, false)
4, ChunkComplete(2902331023, [73, 72, 68, 82])
8, ChunkBegin(1956, [122, 84, 88, 116])
10, Nothing
10, Nothing
10, Nothing
10, Nothing
```

I then ran it bumping the index by the amount consumed:
```
16, ChunkBegin(13, [73, 72, 68, 82])
13, Header(1024, 992, Eight, RGBA, false)
4, ChunkComplete(2902331023, [73, 72, 68, 82])
8, ChunkBegin(1956, [122, 84, 88, 116]) // zTXt
1960, ChunkComplete(3908704955, [122, 84, 88, 116]) // zTXt
```

As you can see, the ChunkComplete reports that it read 1960 bytes, but I can't really get access to it via the decoder's API. Is this a bug or am I missing something?

**Comment by nwin** [comment]
Can you provide an example code an undergraduate reproducing your problem? 

The decoder does handle all chuck types in the same way. So it should work if it works with image data, which it does.

**Comment by robbym** [comment]
Sure:
```
extern crate png;
use png::*;

use std::io::Read;
use std::fs::File;
use std::io::BufReader;

fn main() {
    let mut data = vec![0; 10*1024];
    let mut dmi = BufReader::new(File::open("./floors.dmi").unwrap());
    let n = dmi.read(&mut data).unwrap();

    let mut decoder = StreamingDecoder::new();
    let mut idx = 0;
    let mut found = false;
    for _ in 0..6 {
        let (len, decoded) = decoder.update(&data[idx..idx+1000]).unwrap();
        idx += len;
        println!("{}, {:?}", len, decoded);
    }
}
```
[This is the image I used.](http://i63.tinypic.com/25ic806.png)

Running the above code produces:
```
16, ChunkBegin(13, [73, 72, 68, 82])
13, Header(1024, 992, Eight, RGBA, false)
4, ChunkComplete(2902331023, [73, 72, 68, 82])
8, ChunkBegin(1956, [122, 84, 88, 116])
1000, Nothing
960, ChunkComplete(3908704955, [122, 84, 88, 116])
```

**Comment by nwin** [comment]
Yes you're right it's filtered out. I'll fix that
