### ISSUE TITLE
Problems with publishing

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/image-png#7]
Getting this error when attempting to publish 0.4.0:

```
target/package/png-0.4.0/src/decoder/stream.rs:14:5: 14:12 error: couldn't read "target/package/png-0.4.0/src/decoder/../../inflate/src/lib.rs": No such file or directory (os error 2)
target/package/png-0.4.0/src/decoder/stream.rs:14 mod inflate;
                                                      ^~~~~~~
failed to verify package tarball

Caused by:
  Could not compile `png`.
```

The error does not occur with `cargo build`.

**Comment by bvssvni** [comment]
The problem with publishing is caused by [these lines](https://github.com/PistonDevelopers/image-png/blob/master/src/decoder/stream.rs#L13-L14):

```Rust
// # Development only:
// extern crate inflate;
// # For publishing
#[path = "../../inflate/src/lib.rs"]
mod inflate;
use self::inflate::InflateStream;
```

**Comment by bvssvni** [comment]
I think it makes sense to move "inflate" to its own repo, publish it, and use it as a crates.io dependency.

@nwin Thoughts?

**Comment by bvssvni** [comment]
I moved inflate to its own [repo](https://github.com/PistonDevelopers/inflate). Closing.

**Comment by nwin** [comment]
It does not need its own repo. I don't think it's in a state where any of its APIs should be publish. You can just delete the path.

**Comment by bvssvni** [comment]
@nwin Sorry for messing this up! I thought it would be a good idea to move it for better organizing.

I've already published it on crates.io: https://crates.io/crates/inflate

Do you want me to move it back to the image-png repo?

**Comment by bvssvni** [comment]
I also published a new version of [png](https://crates.io/crates/png) that uses the inflate crate as dependency.

**Comment by nwin** [comment]
Never mind. You can't undo anything on crates.io anyway.
