### ISSUE TITLE
Images must be written all at once or not at all

### ISSUE THREAD

**Issue by ctrlcctrlv** [PistonDevelopers/image-png#75]
Hello,

I'd like to write images so large I cannot store them uncompressed in memory.

As far as I can tell, with the current state of the library, this is impossible. It seems to me that you must either call `png::Writer::write_image_data` with the entire image or not at all. No other function seems to be a candidate for the functionality I'm searching for - we seem to have a `StreamingDecoder` but no `StreamingEncoder`.

I'd love to be proven wrong obviously :-) or any advice you can give for this request. It *is* technically possible - libpng implements it via the `png_write_rows` function.

**Comment by nwin** [comment]
You are right, that is not implemented yet.

Probably it would be wise to implement it in a way that will also accept less than a row, since a row can expand up to 16 GiB in memory.

**Comment by ctrlcctrlv** [comment]
@nwin Any idea of a starting point on how this could be implemented? I wouldn't mind taking a crack at it, could use some fun project after reading that new "Programming Rust" book cover to cover. :-)

**Comment by nwin** [comment]
I would take `write_image_data` as a start and look how you can rewrite the internals to allow pushing partial data. I guess the zlib implementation already supports this which would be the biggest hurdle.

**Comment by nox** [comment]
This would also be useful for Servo.

**Comment by Fuzen-py** [comment]
Is anyone working this?

**Comment by birktj** [comment]
I am going to start working on this, however it seems like at least a full line is needed in memory when filtering is applied. I think I am simply going to create `StreamWriter` struct that implements `Write` and is what you would use to stream data to png file.
